### ISSUE TITLE
bug(documentation): Error! Something went wrong…

### ISSUE THREAD

**Issue by Kristinita** [psmb/typo-reporter#4]
**#2** — similar issue. @dimaip, do you test your steps to reproduce from documentation, use different Google account?

### 1. Summary

If `formId` as in `demo.html`:

    I successful send request, see [**14**](https://docs.google.com/spreadsheets/d/1R5z4waXhx4VsCgkfhZHP_Rvpf6VWQqwmqzpqeulwws8/edit#gid=674370282&range=C14) and [**15**](https://docs.google.com/spreadsheets/d/1R5z4waXhx4VsCgkfhZHP_Rvpf6VWQqwmqzpqeulwws8/edit#gid=674370282&range=C15) lines:

If my `formId`:

    I can't send request. I get an error: `Error! Something went wrong…`.

![Error](https://i.imgur.com/i6Tu1iw.png)

### 2. Example HTML

For example, I have `SashaTypoReporter.html` file as your `demo.html`:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <meta name="viewport" content="width=device-width">

    <title>TypoReporter example</title>
		<style>
			.ReportTypo {font-family: sans; position: fixed; margin: auto; padding: 12px; top: 30%; left: 0; right: 0; max-width: 480px; background: #d7d7d7; border: 1px solid #aaa;}
			.ReportTypo-message {font-family: mono; width: 100%; height: 50px; margin: 12px 0;}
			.ReportTypo-comment {display: block; width: 100%; height: 100px;}
			.ReportTypo-header {font-size: 21px; font-weight: bold;}
			.ReportTypo-label {margin: 12px 0 6px 0;}
			.ReportTypo-heighlight {
				color: red;
				font-weight: bold;
				text-decoration: underline;
			}
		</style>
	</head>
	<body>

		<p>Select some text containing a typo on this page and hit "CTRL+Enter"</p>
		<p>This txet <b>contins</b> a bnuch of typos.</p>
		<script src="https://npmcdn.com/typo-reporter/lib/TypoReporter.min.js"></script>
		<script type="text/javascript">
			var rootNode = document.createElement('div');
			document.body.appendChild(rootNode);

			var typo = new TypoReporter({
				formId: '1FAIpQLSd4bAaZYLlY38abAVosRCuZw9jJpe18sXK522IyftFYQdkvkg'
			}, rootNode);
		</script>
	</body>
</html>

```

### 3. Steps to reproduce

I click to link **<https://docs.google.com/spreadsheets/d/1R5z4waXhx4VsCgkfhZHP_Rvpf6VWQqwmqzpqeulwws8/copy>** → `Make a copy` → I delete text from cells in line 2 and below → I rename spreadsheet → `Tools` → `Notification rules` → I save `Notification rules`:

![Notification rules](https://i.imgur.com/YyB3lar.png)

`Form` → `Edit form` → I copy [**ID from URL**](https://productforums.google.com/forum/#!topic/docs/eoPN9F6KTs4) → I paste ID as value of `formID` variable.

I open `SashaTypoReporter.html` in Firefox → I open Firefox console → I select any text → <kbd>Ctrl+Enter</kbd> → I wrote comment → `Send`.

### 4. Demo behavior

If `formId: '1FAIpQLSd4bAaZYLlY38abAVosRCuZw9jJpe18sXK522IyftFYQdkvkg'` as in `demo.html`:

    success request: `https://cors-anywhere.herokuapp.com/https://docs.google.com/forms/d/e/1FAIpQLSd4bAaZYLlY38abAVosRCuZw9jJpe18sXK522IyftFYQdkvkg/formResponse [HTTP/1.1 200 OK 5599ms]`

![200](https://i.imgur.com/wj0CWYu.png)

**<https://docs.google.com/forms/d/e/1FAIpQLSd4bAaZYLlY38abAVosRCuZw9jJpe18sXK522IyftFYQdkvkg/formResponse>** (pay attention to `/e/`) URL nice open for me.

### 5. my form behavior

If `formId: '1ow-FscGrBaAdixSw_qqIv496tKVkUZxPq1TDO78v__U'` as in my form:

    404 Not Found.

![404](https://i.imgur.com/ol4NJ78.png)

**<https://docs.google.com/forms/d/e/1ow-FscGrBaAdixSw_qqIv496tKVkUZxPq1TDO78v__U/formResponse>** (pay attention to `/e/`) not exist.

![With `/e/`](https://i.imgur.com/NaInsFg.png)

If **<https://docs.google.com/forms/d/1ow-FscGrBaAdixSw_qqIv496tKVkUZxPq1TDO78v__U/formResponse>** (I remove `/e`), page successful open.

#### 6.1. Google

I can't find in Google, what can I do, that URL with `/e/` will correct.

#### 6.2. TypoReporter.min.js

I clone `TypoReporter.min.js` → I add link to `TypoReporter.min.js` in my `SashaTypoReporter.html` → I remove `e/` from link:

+ Find: `= e.endpointUrl || "https://cors-anywhere.herokuapp.com/https://docs.google.com/forms/d/e/" + e.formId`,
+ Replace: `= e.endpointUrl || "https://cors-anywhere.herokuapp.com/https://docs.google.com/forms/d/" + e.formId`

I repeat “steps to reproduce” → request sended, but my sheet [**do not change**](https://docs.google.com/spreadsheets/d/1FNhq7oA6V2_YM9ZF5ZmTL7s-0TVO09iUMzOwL-WjG8Y).

Thanks.

**Comment by dimaip** [comment]
Hi @Kristinita! Thanks for the detailed report!
This url `https://docs.google.com/forms/d/1ow-FscGrBaAdixSw_qqIv496tKVkUZxPq1TDO78v__U/formResponse` redirects me to here: `https://docs.google.com/forms/d/e/1FAIpQLSeWla1h7fXlDjKueBbWAetpZClONavUGcPYlNMKNygveu7q1A/viewform`

`1FAIpQLSeWla1h7fXlDjKueBbWAetpZClONavUGcPYlNMKNygveu7q1A` seems to be the correct id for your form.

So the resulting form submit url would be: `https://docs.google.com/forms/d/e/1FAIpQLSeWla1h7fXlDjKueBbWAetpZClONavUGcPYlNMKNygveu7q1A/formResponse` which seems to work...

I have no idea why those ids differ, would be nice to investigate and update the readme if necessary.

**Comment by dimaip** [comment]
Something must have changed in how Google Forms work with ids. The correct id is now visible in the public form url:

![image](https://user-images.githubusercontent.com/837032/36505156-ad234d64-1763-11e8-80f7-259c4789be16.png)

Could you confirm and update the readme (maybe with pictures?) if possible?

**Comment by Kristinita** [comment]
@dimaip, did you try to create different Google account and test typo-reporter for new account as in your documentation? Possibly, typo-reporter work for your personal Google account and doesn't work for another users due to your personal account binding.

### 1. New steps to reproduce

I click to link **<https://docs.google.com/spreadsheets/d/1R5z4waXhx4VsCgkfhZHP_Rvpf6VWQqwmqzpqeulwws8/copy>** → `Make a copy` → I rename my sheet → more I did not change anything → now my sheet by address **<https://docs.google.com/spreadsheets/d/1P3uVEoxIEA5AdVT-fqQV8FeLepBO3URhOSKMtGivDqM/edit#gid=674370282>**.

`Form` → `Edit form` → `Send` → I click to link symbol.

![Send link](https://i.imgur.com/NYthTgY.png)

I see 2 links:

+ **<https://docs.google.com/forms/d/1YbvRGp3F-E-Dpr07o_FEXTrQ-6xaNJ8yOQJzAckoc0w/edit>** — in URL bar,
+ **<https://docs.google.com/forms/d/e/1FAIpQLSeixkS0E8B2Rfw9PbRDT3VDsJF1uqtv6PJcHGr1G7M6IM6dRw/viewform?usp=sf_link>** — in `Send form`.

I try `1YbvRGp3F-E-Dpr07o_FEXTrQ-6xaNJ8yOQJzAckoc0w` and `1FAIpQLSeixkS0E8B2Rfw9PbRDT3VDsJF1uqtv6PJcHGr1G7M6IM6dRw` as `formID` values → I open `SashaTypoReporter.html` in Firefox → I open Firefox console → I select any text → <kbd>Ctrl+Enter</kbd> → I wrote comment → `Send`. my sheet doesn't change.

Pay attention, that `1FAIpQLSeWla1h7fXlDjKueBbWAetpZClONavUGcPYlNMKNygveu7q1A` is ID for your `demo.html` and for all my copies in `Send form`.

Thanks.

**Comment by dimaip** [comment]
My script doesn't do anything extraordinary... It just submits a Google Form via AJAX, the same way you would submit any other form...

1. Here's your form: https://docs.google.com/forms/d/1YbvRGp3F-E-Dpr07o_FEXTrQ-6xaNJ8yOQJzAckoc0w/viewform?edit_requested=true
Make sure that you can submit to it by hand.
2. Inspect it in devtools of your browser and find its action url. In your case it's `https://docs.google.com/forms/d/e/1FAIpQLSeixkS0E8B2Rfw9PbRDT3VDsJF1uqtv6PJcHGr1G7M6IM6dRw/formResponse`. So your formId should be `1FAIpQLSeixkS0E8B2Rfw9PbRDT3VDsJF1uqtv6PJcHGr1G7M6IM6dRw`, the same id you see in the send form dialog. Try to use it with my script.

If 1) works and 2) doesn't, then there's something wrong with my script, please debug it.
If 1) doesn't work, then Google broke down :)

**Comment by dimaip** [comment]
Ahh, I think it looks like a bug from Google actually.
When I make a copy of the original spreadsheet, go to form, and then open a share dialog, then it points to my original form! Really weird.
You can try to re-create the form manually, or re-link it manually.

**Comment by dimaip** [comment]
> Pay attention, that 1FAIpQLSeWla1h7fXlDjKueBbWAetpZClONavUGcPYlNMKNygveu7q1A is ID for your demo.html and for all my copies in Send form.

Actually it's not, it just starts with the same characters.

Compare `1FAIpQLSeixkS0E8B2Rfw9PbRDT3VDsJF1uqtv6PJcHGr1G7M6IM6dRw` (your id) vs. `1FAIpQLSeWla1h7fXlDjKueBbWAetpZClONavUGcPYlNMKNygveu7q1A` (my id).

**Comment by Kristinita** [comment]
>Actually it's not, it just starts with the same characters.

I'm sorry, I made a mistake.

Now typo-reporter [**successful works for me**](https://docs.google.com/spreadsheets/d/1-qy3qKgr_HFqDlkhAMO2EG9hMK5Qw3dviFYb_1cPzHg).

It would be nice, if you add in README more details, how typo-reporter user can get ID.

Thanks.

**Comment by dimaip** [comment]
@Kristinita could you try to update the readme, maybe with screenshots? I'll review and merge it. I don't have the time to do it myself.

**Comment by Kristinita** [comment]
@dimaip , I prefer put a description to site, not to Readme. [**Arguments**](https://ru.stackoverflow.com/a/686957/199934).

I add to my site [**article**](https://kristinita.ru/IT-articles/typo-reporter) about typo-reporter problems, it solutions and features, that not described in your Readme. If you see typos and/or mistakes in this article, use typo-reporter 😸 .

Thanks.

**Comment by Kristinita** [comment]
@dimaip, you plan to improve typo-reporter? For example, it would be nice, if user, that successful send typo report, would see a message `Your report successful sent!`.

Thanks.

**Comment by dimaip** [comment]
Wow @Kristinita, thanks for the detailed write up! I don't think the typo-reporter is really that size of a project that would benefit from a dedicated site really, after all it's just a matter of a few simple steps to get it running (which are currently not well documented), so I'd really appreciate a PR with the fix to current docs.

I will not add additional features to the project that I would not otherwise need myself (sorry, time constraints), but I will be happy to receive PRs and review them. The open source way, you know :-)

**Comment by Kristinita** [comment]
@dimaip,

> I will not add additional features to the project that I would not otherwise need myself (sorry, time constraints)

User of your site find a typo in your site → user send report via typo-reporter. But how does the user know, send report successful or no? Personally, I would have thought that if there was no message of a successful report, then my report did not send.

I think, It would be nice for you yourself.

Thanks.

**Comment by dimaip** [comment]
@Kristinita yeah, sure, I'd be happy to have it. Will you be able to send a PR?
